language: generic 

sudo: required
services:
  - docker


before_install:
  - docker build -t bstaub/grider_react -f Dockerfile.dev .


script:
  - docker run -e CI=true bstaub/grider_react npm run test